name: SplatoonMC
version: '${project.version}'
main: com.github.tsuoihito.splatoonmc.SplatoonMC
api-version: 1.19
authors: [ tsuoihito ]
commands:
  blockcount:
    permission: splatoonmc.command.blockcount
    usage: |
      /<command> OBJECT PLAYER MATERIAL FROM_X FROM_Y FROM_Z TO_X TO_Y TO_Z
permissions:
  splatoonmc.comamnd.blockcount:
    default: op
